"""
EXStreamTV Constants

Common constants used throughout the application.
"""

# File size constants
KILOBYTE = 1024
MEGABYTE = KILOBYTE * 1024
GIGABYTE = MEGABYTE * 1024

# Default limits
DEFAULT_CHANNEL_LIMIT = 1000
DEFAULT_MEDIA_LIMIT = 10000
DEFAULT_PLAYLIST_LIMIT = 100

# Timeouts
DEFAULT_TIMEOUT = 30
STREAM_TIMEOUT = 60
FFMPEG_TIMEOUT = 300

# Buffer sizes
DEFAULT_BUFFER_SIZE = 64 * KILOBYTE
STREAM_BUFFER_SIZE = 1 * MEGABYTE

# Ollama settings
OLLAMA_DEFAULT_MODEL = "llama3.2"
OLLAMA_DEFAULT_URL = "http://localhost:11434"
DEFAULT_TIMEOUT_SECONDS = 30
PROCESS_CHECK_TIMEOUT = 5

# EPG settings
EPG_ASSIGNMENT_LOG_COUNT = 10
EPG_CATEGORIES_LIMIT = 50
EPG_MAX_PROGRAMS = 1000
EPG_MAX_PROGRAMMES_PER_CHANNEL = 100
EPG_QUERY_LIMIT = 500
EPG_TITLE_TRUNCATE_LENGTH = 100
MAX_EPG_ITEMS_PER_CHANNEL = 100

# Import settings
MAX_IMPORT_FILE_SIZE = 50 * MEGABYTE

# M3U settings
M3U_MAX_ENTRIES = 5000
M3U_FETCH_TIMEOUT = 60
